Repository shivprime94/Data-Structure-Algorithms, pull requests merged in 2021-10, with the labels that each got.

#10 added quick Sort Algo
  QuickSort.cpp
Labels: enhancement, hacktoberfest-accepted

#15 Create sum-even-odd.cpp
  sum-even-odd.cpp
Labels: bug, enhancement, good first issue, hacktoberfest-accepted

#12 Create insertion-sort.cpp
  insertion-sort.cpp
Labels: bug, help wanted, hacktoberfest-accepted

#22 Doraemon Using Python
  doraeomon.py
  factorial.py
  gcd_lcm.py
  guesser.py
  lucky_four.py
Labels: bug, enhancement, hacktoberfest-accepted

#24 Adding operations on datastructures
  Operations on Datastructures/Array Left Rotation.cpp
  Operations on Datastructures/Array Right Rotation.cpp
  Operations on Datastructures/Circular Linked List.cpp
  Operations on Datastructures/Circular Queue Using Array.cpp
  Operations on Datastructures/Intersection_of_2_arrays.cpp
  Operations on Datastructures/Reverse a Linked List using Recusion.cpp
  Operations on Datastructures/Union_of_2_arrays.cpp
Labels: enhancement, hacktoberfest-accepted

#25 This is the solution to Two Sum problem on leetcode
  leetcodeproblems-easy/twoSum.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#27 Create pizzaForces.cpp
  codeforces problem/pizzaForces.cpp
Labels: enhancement, hacktoberfest-accepted

#28 Create twoTables.cpp
  codeforces problem/twoTables.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#29 added Bucket Sort algorithm and codeforces solution
  BucketSort.cpp
  codeforces problem/TRISQ.cpp
Labels: good first issue, hacktoberfest-accepted

#30 Added selection sort
  selectionSort.cpp
Labels: good first issue, hacktoberfest-accepted

#31 Rat in a Maze problem
  Rat in a Maze.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#32 Deleting an element from array By Rahul
  deleting_element.c++
Labels: enhancement, good first issue, hacktoberfest-accepted

#33 added longestANDsubarray problem
  codechef problems/longestANDsubarray.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#210 Added Topological Sorting in Java
  Problems Java/TopologicalSorting.java
Labels: good first issue, hacktoberfest-accepted

#209 Contributes solutions to popular problems
  Algorithms CPP/mergesort.cpp
  Leetcode Problems/NumOfLIS.cpp
Labels: good first issue, hacktoberfest-accepted

#208 Create Max Area Island
  Leetcode Problems/Max Area Island
Labels: good first issue, hacktoberfest-accepted

#207 Add files via upload
  Algorithms CPP/BST.cpp
  Algorithms CPP/queue using arrray.cpp
  Algorithms CPP/queue using linkedlist.cpp
  Algorithms CPP/reverse linkedlist.cpp
  Algorithms CPP/stack using linkedlist.cpp
Labels: good first issue, hacktoberfest-accepted

#206 Create sum_of_integers
  Problems Python/sum_of_integers
Labels: good first issue, hacktoberfest-accepted

#205 Create youtube_video_downloader.py
  python/youtube_video_downloader.py
Labels: good first issue, hacktoberfest-accepted

#204 Create MaximumProfitinJobScheduling.cpp
  leetcode hard/MaximumProfitinJobScheduling.cpp
Labels: good first issue, hacktoberfest-accepted

#203 Create Min no of fountain to cover garden.cpp
  Algorithms CPP/Min no of fountain to cover garden.cpp
Labels: good first issue, hacktoberfest-accepted

#221 Created BinaryTree_VerticalSum.cpp
  Algorithms CPP/BinaryTree_VerticalSum.cpp
Labels: good first issue, hacktoberfest-accepted

#220 Created BinaryTree_AllNodesSum.cpp
  Algorithms CPP/BinaryTree_AllNodesSum.cpp
Labels: good first issue, hacktoberfest-accepted

#219 Created BinaryTree_ReverseLevelOrder.cpp
  Algorithms CPP/BinaryTree_ReverseLevelOrder.cpp
Labels: good first issue, hacktoberfest-accepted

#218 Created BinaryTree_SpiralLevelOrderTraversal.cpp
  Algorithms CPP/BinaryTree_SpiralLevelOrderTraversal.cpp
Labels: good first issue, hacktoberfest-accepted

#217 Created Inorder_without_recursion_BT.cpp
  Algorithms CPP/Inorder_without_recursion_BT.cpp
Labels: good first issue, hacktoberfest-accepted

#216 Created Inorder_successor_BT.cpp
  Algorithms CPP/Inorder_successor_BT.cpp
Labels: good first issue, hacktoberfest-accepted

#215 Created BinaryTree_LevelOrderTraversal.cpp
  Algorithms CPP/BinaryTree_LevelOrderTraversal.cpp
Labels: good first issue, hacktoberfest-accepted

#214 Created nthNode_Inorder_BT.cpp
  Algorithms CPP/nthNode_Inorder_BT.cpp
Labels: good first issue, hacktoberfest-accepted

#213 Creating rock_paper_scissors_game.py
  python/fibonacci_sequence.py
  python/rock_paper_scissors_game.py
Labels: good first issue, hacktoberfest-accepted

#212 Create LCS.cpp
  Algorithms CPP/LCS.cpp
Labels: good first issue, hacktoberfest-accepted

#228 Create Dijkshtra_Shortest_Path_Algo.py
  python/Dijkshtra_Shortest_Path_Algo.py
Labels: hacktoberfest-accepted
