Repository shivprime94/Data-Structure-Algorithms, pull requests merged in 2022-10, with the labels that each got.

#257 DNF (Dutch National Flag) Sort in Cpp
  Algorithms CPP/Dutch_National_Flag_sort.cpp
Labels: hacktoberfest-accepted

#258 TwoSum HashMap O(n) implementation java
  Leetcode Problems/TwoSumHashMap.java
Labels: hacktoberfest-accepted

#292 Happy Number solution added
  leetcodeproblems-easy/HappyNumber.java
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#284 GFG & Leet Code stock buy sell
  GFG/stockBuySell.cpp
  Leet Code/stockyBuySell.cpp
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#291 Longest Common Prefix solution added
  leetcodeproblems-easy/LongestCommonPrefix.java
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#289 Create 3Sum Closest
  Leetcode Problems/3Sum Closest
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#288 I have added stock buy and sell problem solution by cpp.
  stock_buy_and_sell.cpp
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#285 Added Knight's Tour Problem
  CSES Problem Set/Graph/Knight's Tour.cpp
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#286 Vaild_parenthesis_in_java_completed
  valid_parentheseis_in_java.class
  valid_parentheseis_in_java.java
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#287 Tower of Hannoi
  Algorithms CPP/Tower Of Hanoi.cpp
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#290 addded solution for Buy Sell Stock
  leetcodeproblems-easy/BuySellStock.java
Labels: duplicate, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#326 First Missing Positive
  First Missing Positive
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#343 Bubble Sort using Recursion.cpp
  Algorithms CPP/Bubble Sort using Recursion.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#342 Added Download Speed problem in CSES
  CSES Problem Set/Graph/Download Speed.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#341 Divide array into equal pairs program in C++
  Divide array into equal pairs
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#340 CSES - Download Speed
  CSES Problem Set/Graph/download.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#338 Jump Game
  Leetcode Problems/Jump Game
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#337 added Divide Array into Equal Pairs in Java
  Leetcode Easy/Divide_Array_Into_Equal_Pairs.java
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#335 Trapping Rainwater Problem in C++
  Trapping rainwater problem
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#334 Divide Array into Equal Pairs
  Divide Array into Equal Pairs
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#333 Jump Game Leetcode medium
  Jump Game
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#332 Odd Even Linkedlist
  Odd Even Linkedlist
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#331 Minimum Bit Flips to Convert Number program in C++
  Minimum Bit Flips to Convert Number
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#329 Added solution for 1721A- IMAGE problem
  Codeforces Problems/1721A.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#327 Create NthPrime.cpp
  Algorithms CPP/NthPrime.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#363 Create TowerOfHanoi.cpp
  TowerOfHanoi.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#362 Create Optimal Partition of String.cpp
  Leetcode Problems/Optimal Partition of String.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#361 Create Strictly Palindromic Number.cpp
  Leetcode Problems/Strictly Palindromic Number.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#360 Create Partitioning Into Minimum Number Of Deci-Binary Numbers.cpp
  Leetcode Problems/Partitioning Into Minimum Number Of Deci-Binary Numbers.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#359 Create Divide Intervals Into Minimum Number of Groups.cpp
  Leetcode Problems/Divide Intervals Into Minimum Number of Groups.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#358 Create Subrectangle_Queries.cpp
  Leetcode Problems/Subrectangle_Queries.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#357 added WATESTCASES.cpp
  codechef problems/WATESTCASES.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#356 added EQLZING.cpp
  codechef problems/EQLZING.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#355 composite and prime by sangalgovind
  compositeprimeno.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#354 added a stack implementation.
  Algorithms CPP/Stack/nextgreatestelement.cpp
  Algorithms CPP/Stack/stackusingll.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#365 Create MajorityElement.cpp
  MajorityElement.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#371 Queue using Stacks
  Queue using Stacks.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#373 Added Recursive C++ code for gcd (Euclid's Algo).
  Algorithms CPP/gcd_recursive.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#328 First Missing Positive
  First Missing Positive
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#379 Palindrome Linked List
  Leetcode Easy/Palindrome Linked List.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#380 Right view of binary tree
  Random Problems/Right view of binary tree.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#377 twoStack.cpp
  Algorithms CPP/Stack/twoStack.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#376 Added dynamic programming problems
  Leetcode Problems/dungeon_game.cpp
  Leetcode Problems/house_robber.cpp
  Leetcode Problems/house_robber_2.cpp
  Leetcode Problems/house_robber_3.cpp
  Leetcode Problems/longest_common_subsequence.cpp
  Leetcode Problems/longest_increasing_subsequence.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#382 Merge two sorted lists
  Leetcode Easy/Maximum Depth of Binary Tree.cpp
  Leetcode Easy/Merge two sorted lists.cpp
  Random Problems/Right view of binary tree.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#383 added EQDIS.cpp
  codechef problems/EQDIS.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#385 Longest Common Prefix
  Leetcode Easy/Longest Common Prefix
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#386 reverseStack.cpp
  Algorithms CPP/Stack/reverseStack.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#387 Sliding Window Approach
  Algorithms CPP/slidingWindow.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#388 Added Mail Delivery Problem of CSES
  CSES Problem Set/Graph/Mail Delivery.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#402 open_dire
  python/open_dir.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#397 created Readme.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#395 AddedCPPprogram
  ReverseLinkedList.cpp
  primeprint2.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#394 Create Rotate matrix by 90 degree
  Leetcode Problems/Rotate matrix by 90 degree
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#393 added solution to a CSES problem
  CSES Problem Set/Increasing_Array.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#407 CF code added
  hello.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#405 Add Stack Data Structure in Swift
  Swift/Stack/Stack.swift
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#414 Binary Search tree using java
  Binary Search Tree/BinarySearchTree$Node.class
  Binary Search Tree/BinarySearchTree.class
  Binary Search Tree/BinarySearchTree.java
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#415 Added binary to decimal
  python/bynary_to_decimal.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#416 Add Hash Table Data Structure in Go
  Go/Data-Structures/Hash-Table/main.go
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#417 Add Single Linked List Data Structure in Go
  Go/Data-Structures/Single-Linked-List/main.go
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#418 Create analogClock.py
  python/analogClock.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#419 Add Binary Search Tree Data Structure in Go
  Go/Data-Structures/Binary-Search-Tree/main.go
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#420 Created mergesort.cpp
  mergesort.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#426 Contributed 2D Array & Lunch-Time Codes
  Algorithms CPP/2D arrays/2dArrayIntro.cpp
  Algorithms CPP/2D arrays/Search2DMatrix1.java
  Algorithms CPP/2D arrays/Search2DMatrix2.java
  Algorithms CPP/2D arrays/SpiralPrint.java
  Algorithms CPP/2D arrays/WavePrint.java
  Algorithms CPP/2D arrays/search2DMatrix1.cpp
  Algorithms CPP/2D arrays/search2DMatrix2.cpp
  Algorithms CPP/2D arrays/spiralPrint.cpp
  Algorithms CPP/2D arrays/wavePrint.cpp
  codechef problems/July Lunchtime 2022 (LTIME110D)/EZSPEAK.cpp
  codechef problems/July Lunchtime 2022 (LTIME110D)/INTRDSGN.cpp
  codechef problems/July Lunchtime 2022 (LTIME110D)/LARGEFAM.cpp
  codechef problems/July Lunchtime 2022 (LTIME110D)/LASTLEVELS.cpp
  codechef problems/July Lunchtime 2022 (LTIME110D)/MAKEPALAGAIN.cpp
  codechef problems/July Lunchtime 2022 (LTIME110D)/TFPAPER.cpp
  codechef problems/May Lunchtime 2022 (LTIME108D)/APPLORNG.cpp
  codechef problems/May Lunchtime 2022 (LTIME108D)/PRACLIST.cpp
  codechef problems/May Lunchtime 2022 (LTIME108D)/TODOLIST.cpp
  codechef problems/May Lunchtime 2022 (LTIME108D)/WATERFLOW.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#432 added deleteMiddleElementStack.cpp
  Algorithms CPP/Stack/deleteMiddleElementStack.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#431 Create IntegerToRoman.cpp
  Leetcode Problems/IntegerToRoman.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#436 Create Create Create Fitting The Array.cpp
  Algorithms CPP/Create Create Fitting The Array.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#435 Create Create Fitting The Array.cpp
  Algorithms CPP/Create Fitting The Array.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#434 Array Rotation.cpp
  Array_Rotation.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#438 hacktoberfest2022
  Floyd_Triangle.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#439 Flattening a Linked List
  GFG/FlatteningLL.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#441 Create Recover Binary Search Tree.cpp
  Algorithms CPP/Recover Binary Search Tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#442 Create Unique Binary Search Trees.cpp
  Algorithms CPP/Unique Binary Search Trees.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#450 Create Smallest positive missing.cpp
  Algorithms CPP/2D arrays/Smallest positive missing.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#449 Create Minimum Platform.cpp
  Algorithms CPP/2D arrays/Minimum Platform.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#448 Leetcode Medium Problem added
  Codeforces Problems/719E-Arranging The Sheep.py
  Leetcode Problems/medium/12 Integer to Roman.py
  Leetcode Problems/medium/692 Top K Frequent Words.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#447 Create Majority Element.cpp
  Algorithms CPP/2D arrays/Majority Element.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#446 Create Array waveform.cpp
  Algorithms CPP/2D arrays/Array waveform.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#445 Create Trappinf rainwater.cpp
  Algorithms CPP/2D arrays/Trappinf rainwater.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#444 Kth largest element in an array
  leetcodeproblems/medium/kth largest element in an array.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#443 contribution guideline . md
  contribution guideline . md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#451 Create MergeKSortedLists.cpp
  leetcode hard/MergeKSortedLists.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#466 Create CustomHashFunction.cpp
  CustomHashFunction.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#465 Create zFunction.cpp
  zFunction.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#463 Create Lis.cpp
  Lis.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#461 Create Iterative Fast Fourier Transformation for polynomial multiplic…
  Iterative Fast Fourier Transformation for polynomial multiplication
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#460 Create Tower of Hanoi using recursion (C++ program)
  Tower of Hanoi using recursion (C++ program)
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#459 Create Find number of endless points in cpp
  Find number of endless points in cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#457 Create Maximum number of segments of lengths a, b and c in cpp
  Maximum number of segments of lengths a, b and c in cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#455 Create Job_scheduling.cpp
  Job_scheduling.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#454 Create Kruskal.cpp
  Kruskal.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#453 Create minProductSubset.cpp
  minProductSubset.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#473 RedBlackTree and ToerOfHanoi
  Algorithms CPP/RedBlackTree.cpp
  Algorithms CPP/TowerOfHanoi.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#472 Leetcode Daily + Leetcode Medium Problems added
  Leetcode Problems/medium/76.Minimum Window Substring.py
  Leetcode Problems/medium/8.String to Integer (atoi).py
  Leetcode Problems/medium/Jump Game II.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#471 Added Remove Element in Leetcode Easy
  Leetcode Easy/RemoveElement.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#477 Create monsters.cpp
  CSES Problem Set/monsters.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#478 Added solution to a problem
  Leetcode Problems/largest_rectangle_in_histogram.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#479 code added
  CSES Problem Set/Round Trip.cpp
  CSES Problem Set/Shortest Routes I.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#480 Find a cycle in a linked list
  Leetcode Problems/list_cycle.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#481 Create divisible_numbers.cpp
  Codeforces Problems/divisible_numbers.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#482 solution to reverse linked list
  Leetcode Problems/reverse_linked_list.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#483 Create Shortest Routes II.cpp
  CSES Problem Set/Shortest Routes II.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#484 Create number_game.cpp
  Codeforces Problems/number_game.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#486 Create Building Roads.cpp
  CSES Problem Set/Building Roads.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#487 adding a new file
  Leetcode Problems/rain_water_trapped.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#488 Create fish.cpp
  Codeforces Problems/fish.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#489 Create Message Route.cpp
  CSES Problem Set/Message Route.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#490 Create sort_zero.cpp
  Codeforces Problems/sort_zero.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#492 Create code.cpp
  Codeforces Problems/code.cpp
  Codeforces Problems/color.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#493 Create color2.cpp
  Codeforces Problems/color2.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#494 Create color3.cpp
  Codeforces Problems/color3.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#495 Create sum game.cpp
  Codeforces Problems/sum game.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#496 Created N- Queen.cpp
  N- Queen.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#476 Added 38. Count and Say solution in C++.
  Leetcode Problems/Count ans Say.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#475 Added N-Queens problem
  Leetcode Problems/51. N-Queens
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#498 Contributed some codechef problems related to DS
  codechef problems/EMPR.cpp
  codechef problems/EXPRESSION_3.cpp
  codechef problems/KNGATK.cpp
  codechef problems/LLMID.cpp
  codechef problems/LUCNUM.cpp
  codechef problems/MONSTER1.cpp
  codechef problems/RTLL.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#497 Factors of a number
  Problems Python/factors.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#474 Create Queue_using_single_Stack.cpp
  Queue_using_single_Stack.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#427 Added Stack and Queue problems
  Algorithms CPP/Queue/KQueue.cpp
  Algorithms CPP/Queue/circularQueue.cpp
  Algorithms CPP/Queue/circularTour.cpp
  Algorithms CPP/Queue/deque.cpp
  Algorithms CPP/Queue/implementQueue.cpp
  Algorithms CPP/Queue/negativeInteger.cpp
  Algorithms CPP/Queue/nonRepeating.cpp
  Algorithms CPP/Queue/queueIntro.cpp
  Algorithms CPP/Queue/reverseFirstK.cpp
  Algorithms CPP/Queue/reverseQueue.cpp
  Algorithms CPP/Queue/sumMaxMin.cpp
  Algorithms CPP/Stack/bracketReversals.cpp
  Algorithms CPP/Stack/deleteMiddle.cpp
  Algorithms CPP/Stack/insertAtBottom.cpp
  Algorithms CPP/Stack/redundantBrackets.cpp
  Algorithms CPP/Stack/reverseStack.cpp
  Algorithms CPP/Stack/reverseString.cpp
  Algorithms CPP/Stack/validBrackets.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#501 Some questions on Binary Tree using Python is added.
  Binary_Tree_Using_Python/Depth_of_BT.py
  Binary_Tree_Using_Python/check_both_tree_is_same.py
  Binary_Tree_Using_Python/dfs_traversals_BT.py
  Binary_Tree_Using_Python/find_leaf_node_of_BT.py
  Binary_Tree_Using_Python/invert_a_BT.py
  Binary_Tree_Using_Python/leaf_similar_tree.py
  Binary_Tree_Using_Python/left_view_of_Bt.py
  Binary_Tree_Using_Python/no_of_node_in_BT.py
  Binary_Tree_Using_Python/path_sum_compare_with__target_sum.py
  Binary_Tree_Using_Python/path_sum_of_BT.py
  Binary_Tree_Using_Python/print_all_nodes_dont_have_siblings.py
  Binary_Tree_Using_Python/sum_of_left_leaf_node.py
  Binary_Tree_Using_Python/sum_of_root_to_leaf_paths.py
  Binary_Tree_Using_Python/univalued_BT.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#502 Added Python Code for Minimum path sum in a Matrix. DP solution with memoization, Tabulation & Space Optimize
  python/min_path_sum.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#503 Following Approach to solve the Merge Interval problem with the help of Stack and indexing in Python.
  python/Merge Overlapping Intervals.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#504 minimum window substring
  leetcode hard/minimum_window_substring.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#505 Highest Mountain added
  Leetcode Problems/HighestMountainInArray.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#508 Floyd–Warshall Algorithm
  Algorithms in C#/Dijkstra-Algorithm.cs
  Algorithms in C#/Floyd-Warshall-Algorithm.cs
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#513 Max Circular Subarray Sum
  GFG/Max_Circular_Subarray_Sum.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#518 Contributed codes related to new conceptual series of codechef
  codechef problems/DSAPREP_01 - Basic Programming - Easy/EMPR.cpp
  codechef problems/DSAPREP_01 - Basic Programming - Easy/EXPRESSION_3.cpp
  codechef problems/DSAPREP_01 - Basic Programming - Easy/KNGATK.cpp
  codechef problems/DSAPREP_01 - Basic Programming - Easy/LUCNUM.cpp
  codechef problems/DSAPREP_01 - Basic Programming - Easy/MONSTER1.cpp
  codechef problems/DSAPREP_08 - Linked List/LLMID.cpp
  codechef problems/DSAPREP_08 - Linked List/RTLL.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#516 Kadanes_Algorithm
  GFG/Kadanes_Algorithm.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#515 Multiply Strings
  Leetcode Problems/Multiply_Strings.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#524 Create Multiply Strings
  Leetcode Problems/medium/43. Multiply Strings.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#523 leetcode hard + Lc daily Problem added + few leetcode medium
  Leetcode Problems/medium/17. Letter Combinations of a Phone Number.py
  Leetcode Problems/medium/25. Reverse Nodes in k-Group.py
  Leetcode Problems/medium/image Overlap.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#521 Create Shortest Distance in a Binary Maze.cpp
  Shortest Distance in a Binary Maze.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#520 Added Some Algorithms for Certain Problems
  CSES Problem Set/Searching and Sorting/Playlist.cpp
  CSES Problem Set/Searching and Sorting/Towers.cpp
  Codeforces Problems/1420C1 Pokemon Army(easy).cpp
  Codeforces Problems/1420C2 - Pokemon Army(hard).cpp
  Codeforces Problems/1708C - Doremy's IQ.cpp
  Codeforces Problems/1709C - Recover an RBS.cpp
  Codeforces Problems/1721C - MinMax Array Transformation.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022
